### ISSUE TITLE
Qr code has too much data

### ISSUE THREAD

**Issue by KenN7** [KenN7/KorreKthor#1]
Writing full json has a lot of redundancy and noise (field names, brackets, etc.).
The data in the qr code should be simpler, just:
```
Matricule;Version;LessonId
```
or
```
Matricule\nVersion\nLessonId
```
This could improve qrcode readability by making the image dimension smaller, allowing more qrcode error protection for less pixels in the page.

**Comment by ThomasVandermeersch** [comment]
Done : https://github.com/ThomasVandermeersch/KorreKthor/commit/79768ca799bc5655fefb515c2fa64a003e6e2920

**Comment by KenN7** [comment]
Fixed by 79768ca799bc5655fefb515c2fa64a003e6e2920 and 1d8e0a6cefcae283d7ba4c2b04c3f897b1d88b5f
