### ISSUE TITLE
img processing should return integers matrix instead of bool

### ISSUE THREAD

**Issue by KenN7** [KenN7/KorreKthor#3]
To account for uncertainty for some partially checked results, and display it in the web interface

**Comment by KenN7** [comment]
Img processing part done in 23b21de5ff4d788d4fbad4e664899cdebea91001
Web app needs to be fixed accordlingy

**Comment by ThomasVandermeersch** [comment]
Web app correction fixed : https://github.com/ThomasVandermeersch/KorreKthor/commit/871f33fed47e67887910b9edb3660f7da58a8849
